"""
ThinkingEngine Integration — connects the ThinkingManager to the main tick pipeline.

Manages thought generation frequency, per-type cooldowns, ICRI gating, and
emotion-biased type selection. Generated thoughts are stored in the
AutobiographicalStore for long-term memory.

Requirements: 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7
"""

import time
import logging
from dataclasses import dataclass, field
from typing import Optional, List, Dict

logger = logging.getLogger(__name__)


@dataclass
class Thought:
    """A spontaneous internal thought generated by the ThinkingEngine."""

    type: str  # One of THOUGHT_TYPES
    content: str  # Natural language thought content
    timestamp: float = field(default_factory=time.time)
    triggered_by: str = ""  # Dominant emotional system that triggered this


THOUGHT_TYPES: List[str] = [
    "episodic_fragment",
    "counterfactual",
    "future_projection",
    "self_question",
    "free_association",
    "rumination",
]

# Emotion → thought type bias mapping
# Maps dominant Panksepp system to preferred thought categories
EMOTION_THOUGHT_BIAS: Dict[str, List[str]] = {
    "PANIC": ["rumination", "future_projection"],  # worry-type
    "FEAR": ["rumination", "future_projection"],  # worry-type
    "SEEKING": ["free_association", "self_question"],  # curiosity-type
    "PLAY": ["free_association", "episodic_fragment"],  # playful recall
    "CARE": ["episodic_fragment", "future_projection"],  # nurturing recall
    "RAGE": ["counterfactual", "rumination"],  # frustration loops
    "LUST": ["future_projection", "free_association"],  # desire projection
}


class ThinkingEngineIntegration:
    """
    Integration layer connecting thinking.py to the main tick pipeline.

    Manages thought generation frequency, cooldowns, and ICRI gating.
    Thoughts are biased by the dominant Panksepp system and have per-type
    cooldowns to prevent repetitive thought loops.
    """

    GENERATION_INTERVAL: float = 5.0  # seconds between thoughts
    COOLDOWN_PER_TYPE: float = 30.0  # seconds before same type can repeat
    ICRI_THRESHOLD: float = 0.10  # minimum ICRI for thought generation

    def __init__(self, thinking_engine, autobio_store):
        """
        Args:
            thinking_engine: ThinkingManager instance from thinking.py
            autobio_store: AutobiographicalStore for persisting generated thoughts
        """
        self._engine = thinking_engine
        self._autobio = autobio_store
        self._last_generation: float = 0.0
        self._type_cooldowns: Dict[str, float] = {}  # type → last_generated_timestamp

    def should_generate(self, icri: float, dmn_active: bool, now: float) -> bool:
        """Check if conditions allow thought generation.

        Suppresses generation when:
        - ICRI < 0.10 (consciousness too low)
        - DMN is inactive (external focus mode)
        - Less than GENERATION_INTERVAL seconds since last thought

        Args:
            icri: Current ICRI (consciousness richness) value
            dmn_active: Whether the Default Mode Network is active
            now: Current timestamp (seconds since epoch)

        Returns:
            True if thought generation is permitted
        """
        if icri < self.ICRI_THRESHOLD:
            return False
        if not dmn_active:
            return False
        if (now - self._last_generation) < self.GENERATION_INTERVAL:
            return False
        return True

    def get_biased_types(self, dominant_system: str) -> List[str]:
        """Return thought types biased by dominant emotional system.

        Uses EMOTION_THOUGHT_BIAS mapping to select types appropriate
        for the current emotional state. Falls back to first two
        THOUGHT_TYPES if the system is not in the mapping.

        Args:
            dominant_system: Current dominant Panksepp system name

        Returns:
            List of thought type strings biased toward the emotion
        """
        return EMOTION_THOUGHT_BIAS.get(dominant_system, THOUGHT_TYPES[:2])

    def is_type_on_cooldown(self, thought_type: str, now: float) -> bool:
        """Check if a thought type is in its 30-second cooldown period.

        Args:
            thought_type: The thought type to check
            now: Current timestamp

        Returns:
            True if the type was generated less than 30 seconds ago
        """
        last = self._type_cooldowns.get(thought_type, 0.0)
        return (now - last) < self.COOLDOWN_PER_TYPE

    def generate(self, state) -> Optional[Thought]:
        """Attempt to generate a thought based on current HeliosState.

        Returns None if generation is suppressed (ICRI too low, DMN inactive,
        interval not elapsed, or all biased types on cooldown).

        Generated thoughts are stored in the AutobiographicalStore.

        Args:
            state: HeliosState instance with current tick state

        Returns:
            Thought instance if generated, None otherwise
        """
        now = time.time()

        # Use state.icri (phi property maps to icri for backward compat)
        icri = state.icri if hasattr(state, "icri") else getattr(state, "phi", 0.0)

        # Determine DMN activity — if the thinking engine has a mode,
        # DMN is active when not in external focus mode
        dmn_active = True
        if hasattr(self._engine, "current_mode"):
            # ThinkingManager.MODE_EXTERNAL means external focus (DMN off)
            dmn_active = self._engine.current_mode != getattr(
                self._engine, "MODE_EXTERNAL", "external"
            )

        if not self.should_generate(icri, dmn_active, now):
            return None

        # Get emotion-biased types and filter by cooldown
        biased_types = self.get_biased_types(state.dominant_system)
        available = [t for t in biased_types if not self.is_type_on_cooldown(t, now)]

        if not available:
            # All biased types on cooldown — try remaining types
            all_remaining = [
                t
                for t in THOUGHT_TYPES
                if t not in biased_types and not self.is_type_on_cooldown(t, now)
            ]
            if not all_remaining:
                return None
            available = all_remaining

        thought_type = available[0]

        # Generate thought content via the underlying ThinkingManager
        content = self._generate_content(thought_type, state)
        if not content:
            return None

        # Create Thought instance
        thought = Thought(
            type=thought_type,
            content=content,
            timestamp=now,
            triggered_by=state.dominant_system,
        )

        # Update tracking state
        self._last_generation = now
        self._type_cooldowns[thought_type] = now

        # Store in autobiographical memory
        self._store_thought(thought, state)

        logger.debug(
            f"Generated thought: [{thought_type}] triggered_by={state.dominant_system}"
        )

        return thought

    def _generate_content(self, thought_type: str, state) -> str:
        """Generate thought content using the underlying ThinkingManager.

        Maps our thought_type taxonomy to ThinkingManager's generation modes.

        Args:
            thought_type: One of THOUGHT_TYPES
            state: Current HeliosState

        Returns:
            Generated thought content string, or empty string on failure
        """
        try:
            # Map thought types to ThinkingManager source categories
            source_map = {
                "episodic_fragment": "memory_replay",
                "counterfactual": "counterfactual",
                "future_projection": "counterfactual",
                "self_question": "free_association",
                "free_association": "free_association",
                "rumination": "memory_replay",
            }

            panksepp = getattr(state, "panksepp", {})
            valence = getattr(state, "valence", 0.0)
            arousal = getattr(state, "arousal", 0.0)

            # Use ThinkingManager.generate_thoughts if available
            if hasattr(self._engine, "generate_thoughts"):
                fragments = self._engine.generate_thoughts(
                    valence=valence,
                    arousal=arousal,
                    panksepp_state=panksepp,
                    limit=1,
                )
                if fragments:
                    return fragments[0].content
            
            # Fallback: generate a simple introspective thought
            return self._fallback_content(thought_type, state)

        except Exception as e:
            logger.warning(f"Thought generation failed: {e}")
            return ""

    def _fallback_content(self, thought_type: str, state) -> str:
        """Generate fallback thought content when ThinkingManager produces nothing.

        Args:
            thought_type: The type of thought to generate
            state: Current HeliosState

        Returns:
            A simple thought content string
        """
        dominant = getattr(state, "dominant_system", "")
        templates = {
            "episodic_fragment": f"回想起之前的感受... ({dominant})",
            "counterfactual": "如果当时不一样的话...",
            "future_projection": "接下来会怎样呢...",
            "self_question": "我现在是什么状态？",
            "free_association": "思绪飘向了远方...",
            "rumination": f"一直在想着... ({dominant})",
        }
        return templates.get(thought_type, "...")

    def _store_thought(self, thought: Thought, state) -> None:
        """Store a generated thought in the AutobiographicalStore.

        Args:
            thought: The generated Thought instance
            state: Current HeliosState for context
        """
        try:
            panksepp = getattr(state, "panksepp", {})
            valence = getattr(state, "valence", 0.0)
            arousal = getattr(state, "arousal", 0.0)
            icri = state.icri if hasattr(state, "icri") else getattr(state, "phi", 0.0)

            self._autobio.record(
                panksepp=panksepp,
                valence=valence,
                arousal=arousal,
                dominant=thought.triggered_by,
                phi=icri,
                narrative=f"[{thought.type}] {thought.content}",
                event_trigger=f"thought:{thought.type}",
            )
        except Exception as e:
            logger.warning(f"Failed to store thought in autobio: {e}")
